### ISSUE TITLE
API returning Status Code 2806 while publishing

### ISSUE THREAD

**Issue by ManishPatiyal** [blocoio/cardcase#1]
I have tried to build your app using my API_KEYS.It is giving me error "Could not connect.Please confirm internet is available and try again".But my internet is working perfectly.
I have also checked that it is returning "unknown status code 2806" while publishing the message.

**Comment by sdsantos** [comment]
Hi @ManishPatiyal ,

It might be an issue with permissions. Have you enabled the Nearby Messages API on your Google Dev Console? And have you added your SHA-1 fingerprint?

Basically it's this steps right here that you need to check: https://developers.google.com/nearby/messages/android/get-started
