### ISSUE TITLE
Publish APK on Github?

### ISSUE THREAD

**Issue by IzzySoft** [blocoio/cardcase#3]
Are you planning to publish the `.apk` file here on Github, so people w/o Playstore can grab it? Best place would be with your `releases/`, see [Creating Releases](https://help.github.com/articles/creating-releases/).

**Comment by IzzySoft** [comment]
Hm. Project abandoned? :scream_cat:

**Comment by sdsantos** [comment]
@IzzySoft totally lost the notification on this. That's a good idea! Here it is: https://github.com/blocoio/cardcase/releases/tag/1.0.3

**Comment by IzzySoft** [comment]
Happens :) Thanks a lot! I've [integrated your app](https://apt.izzysoft.de/fdroid/index/apk/io.bloco.cardcase) with my F-Droid compatible repo, so folks without Playstore have a way to easily install and update it. Updates will usually be available within 24h of your creating a new tag and attaching the `.apk` to it. If you'd consider an APK without Analytics modules (Crashlytics, GA) I could remove the corresponding AntiFeature from the description :wink: Just let me know then.

**Comment by sdsantos** [comment]
Thank you @IzzySoft, that's nice ;)

**Comment by IzzySoft** [comment]
Glad you like it! To pick up at this point: would you consider a build without GA, Firebase and Crashlytics – so we could drop that Tracking AntiFeature? If you could also build without GMS, I suspect the app would even be eligible to enter F-Droid's main repository.

**Comment by sdsantos** [comment]
@IzzySoft I get the point, and it shouldn't be too hard. But right now I don't have the time to do it. I'll take note for the next time I'm picking on our open source projects.
