### ISSUE TITLE
Bug report on card case

### ISSUE THREAD

**Issue by idimummy** [blocoio/cardcase#5]
#### Expected behavior
User should be able share card. 

#### Actual behavior
Application pops up error when trying to share card.

#### How to reproduce
Download card case from play store [here](https://play.google.com/store/apps/details?id=io.bloco.cardcase), launch it, create the contact details you would like to share, select to share card  

* Operating system:Android Version 7.0  
* Device used: Tecno Boom J8

#### Recording Of The Bug
https://youtu.be/hZ2Q9sFMtqY
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@kennykajo/bug-report-on-card-case">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by sdsantos** [comment]
@idimummy thank you for the bug report and the video.

This is not simple to troubleshoot from my end, since it didn't seem to send any error report. Is there any chance Google Nearby is not supported on your device?

**Comment by CCsoh** [comment]
same here I m using Huawei mate10, application pops up error when I trying to share the card

**Comment by sdsantos** [comment]
This issue was probably fix with the latest Card Case release.
